console.log("1st statement");
console.log("2st statement");
debugger;
console.log("3st statement");
console.log("4st statement");
debugger;
console.log("5st statement");
console.log("5st statement");
debugger;
console.log("5st statement");
console.log("6st statement");
